name: mall
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttertoast: ^7.0.4
  vertical_tabs: ^0.2.0
  flutter_swiper: ^1.1.6
  flutter_rating_bar: ^3.0.1+1
  image_picker: ^0.6.7+7
  webview_flutter: ^0.3.22+1
  shared_preferences: ^0.5.12
  zego_express_engine: ^1.15.0
  zego_permission:
    git:
      url: git://github.com/zegoim/zego-flutter-permission.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

